ServerAlias *
Listen 0.0.0.0:631

Browsing On
WebInterface Yes
DefaultAuthType None
DefaultEncryption Never
BrowseLocalProtocols dnssd
DefaultShared Yes


# Prevent container from shutting down CUPS
# (CUPS upstream defaults to IdleExitTimeout 60)
IdleExitTimeout 0

# Allow access to the server
<Location />
  Allow All
</Location>

# Allow access to the admin interface
<Location /admin>
  Allow All
</Location>

# Allow access to admin configuration
<Location /admin/conf>
  Allow All
</Location>
